import type { Metadata } from "next";

import "./globals.css";
import Navbar from "@/components/shared/Navbar/Navbar";
import { Space_Grotesk } from "next/font/google";

const grotesque = Space_Grotesk({
  subsets: ["latin"],
  weight: ["400", "500", "700"], // adjust as needed
  
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${grotesque} antialiased`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
